// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI4hozM7feODBAM-O_x09C5s355DzOhHs',
    appId: '1:602351514125:web:0c56fb864ce5724b8e9b44',
    messagingSenderId: '602351514125',
    projectId: 'contact-list-firebase-97a94',
    authDomain: 'contact-list-firebase-97a94.firebaseapp.com',
    databaseURL: 'https://contact-list-firebase-97a94-default-rtdb.firebaseio.com',
    storageBucket: 'contact-list-firebase-97a94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvRXv04L0agR9HZj4P7PTy6sdcYXfbnJE',
    appId: '1:602351514125:android:1f84bb24b75435808e9b44',
    messagingSenderId: '602351514125',
    projectId: 'contact-list-firebase-97a94',
    databaseURL: 'https://contact-list-firebase-97a94-default-rtdb.firebaseio.com',
    storageBucket: 'contact-list-firebase-97a94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFM-VTZy-o7Txok8LQKEgbHmyB9HJ2e0c',
    appId: '1:602351514125:ios:d515ac297880cd068e9b44',
    messagingSenderId: '602351514125',
    projectId: 'contact-list-firebase-97a94',
    databaseURL: 'https://contact-list-firebase-97a94-default-rtdb.firebaseio.com',
    storageBucket: 'contact-list-firebase-97a94.appspot.com',
    iosBundleId: 'com.example.projectImpacta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFM-VTZy-o7Txok8LQKEgbHmyB9HJ2e0c',
    appId: '1:602351514125:ios:d515ac297880cd068e9b44',
    messagingSenderId: '602351514125',
    projectId: 'contact-list-firebase-97a94',
    databaseURL: 'https://contact-list-firebase-97a94-default-rtdb.firebaseio.com',
    storageBucket: 'contact-list-firebase-97a94.appspot.com',
    iosBundleId: 'com.example.projectImpacta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI4hozM7feODBAM-O_x09C5s355DzOhHs',
    appId: '1:602351514125:web:99315bc1f108d1d18e9b44',
    messagingSenderId: '602351514125',
    projectId: 'contact-list-firebase-97a94',
    authDomain: 'contact-list-firebase-97a94.firebaseapp.com',
    databaseURL: 'https://contact-list-firebase-97a94-default-rtdb.firebaseio.com',
    storageBucket: 'contact-list-firebase-97a94.appspot.com',
  );
}
